[package]
name = "control_box_simulator"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[dependencies]
r2r = "0.5.3"
futures = "0.3.15"
tokio = { version = "1", features = ["full"] }

[workspace]
