[package]
name = "sp_model"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[[bin]]
name = "cylinders"
path = "src/cyliders.rs"

[[bin]]
name = "cylinders2"
path = "src/cylinders2.rs"

[[bin]]
name = "cylinders2_structs"
path = "src/cylinders2_structs.rs"

[dependencies]
# sp-domain = { path = "/home/martin/sp/sp-domain" }
# sp-runner = { path = "/home/martin/sp/sp-runner" }
sp-domain = { git = "https://github.com/sequenceplanner/sp-rust", rev = "cae824b" }
sp-runner = { git = "https://github.com/sequenceplanner/sp-rust", rev = "cae824b" }

sp-resources = {path = "../sp_resources/"}

failure = "0.1.5"

[dev-dependencies]
serial_test = "0.5.0"
