[package]
name = "sp_model"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[features]
default = ["ros"]
ros = ["sp-runner/ros"]

[dependencies]
# sp-domain = { path = "/Users/martin/sp/sp-rust/sp-domain" }
# sp-runner = { path = "/Users/martin/sp/sp-rust/sp-runner" }
sp-domain = { git = "https://github.com/sequenceplanner/sp-rust", branch = "actions" }
sp-runner = { git = "https://github.com/sequenceplanner/sp-rust", branch = "actions" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
serial_test = "0.5.0"
